-- Create database
CREATE DATABASE private_school;

USE private_school;

-- Create tables
CREATE TABLE courses (
	course_id int NOT NULL AUTO_INCREMENT,
    title varchar(45),
    stream varchar(45),
    type varchar(45),
    start_date date,
    end_date date,
    PRIMARY KEY(course_id)
);

CREATE TABLE students (
	student_id int NOT NULL AUTO_INCREMENT,
    first_name varchar(45),
    last_name varchar(45),
    dateOfBirth date,
    tuition_fees int,
    PRIMARY KEY(student_id)
);

CREATE TABLE trainers (
	trainer_id int NOT NULL AUTO_INCREMENT,
    first_name varchar(45),
    last_name varchar(45),
    subject varchar(45),
    PRIMARY KEY(trainer_id)
);

CREATE TABLE assignments (
	assignment_id int NOT NULL AUTO_INCREMENT,
    title varchar(45),
    description varchar(300),
    subDateTime date,
    oral_mark int,
    total_mark int,
    PRIMARY KEY(assignment_id)
);

CREATE TABLE studentsPerCourse (
	studentPerCourse_id int NOT NULL AUTO_INCREMENT,
    student_id int,
    course_id int,
    PRIMARY KEY(studentPerCourse_id),
    FOREIGN KEY(student_id) REFERENCES students(student_id),
    FOREIGN KEY(course_id) REFERENCES courses(course_id)
);

CREATE TABLE trainersPerCourse (
	trainerPerCourse_id int NOT NULL AUTO_INCREMENT,
    trainer_id int,
    course_id int,
    PRIMARY KEY(trainerPerCourse_id),
    FOREIGN KEY(trainer_id) REFERENCES trainers(trainer_id),
    FOREIGN KEY(course_id) REFERENCES courses(course_id)
);

CREATE TABLE assignmentsPerCourse (
	assignmentPerCourse_id int NOT NULL AUTO_INCREMENT,
    course_id int,
    assignment_id int,
    PRIMARY KEY(assignmentPerCourse_id),
    FOREIGN KEY(course_id) REFERENCES courses(course_id),
    FOREIGN KEY(assignment_id) REFERENCES assignments(assignment_id)
);

CREATE TABLE assignmentsPerStudentPerCourse (
	assignmentsPerStudentPerCourse_id int NOT NULL AUTO_INCREMENT,
    assignment_id int,
    student_id int,
    course_id int,
    PRIMARY KEY(assignmentsPerStudentPerCourse_id),
    FOREIGN KEY(student_id) REFERENCES students(student_id),
    FOREIGN KEY(assignment_id) REFERENCES assignments(assignment_id),
    FOREIGN KEY(course_id) REFERENCES courses(course_id)
);



-- Populate the tables of the database with enough data
INSERT INTO courses (title, stream, type, start_date, end_date) VALUES ("CB21JSFT","JavaScript","Full-time","2021/10/18","2022/01/18"),
																	   ("CB21JSPT","JavaScript","Part-time","2021/10/18","2022/04/28"),
                                                                       ("CB21PHFT","Python","Full-time","2021/10/18","2022/01/18"),
                                                                       ("CB21PHPT","Python","Part-time","2021/10/18","2022/04/28"),
                                                                       ("CB21JVFT","Java","Full-time","2021/10/18","2022/01/18"),
                                                                       ("CB21JVPT","Java","Part-time","2021/10/18","2022/04/28"),
                                                                       ("CB21C#FT","C#","Full-time","2021/10/18","2022/01/18"),
                                                                       ("CB21C#PT","C#","Part-time","2021/10/18","2022/04/28");
                                                                      
                                                                      
INSERT INTO students (first_name, last_name, dateOfBirth, tuition_fees) VALUES ("Harry", "Potter", "1990/04/15", 2500),
																			   ("Jon", "Snow", "1985/05/19", 2500),
                                                                               ("John", "Osbourne", "1986/08/13", 2500),
                                                                               ("Bruce", "Dickinson", "1989/07/20", 2500),
                                                                               ("Peter", "Graham", "1991/02/27", 2500),
                                                                               ("Isabella", "Fernandez", "1993/03/10", 2500),
                                                                               ("Anya", "West", "1989/01/11", 2500),
                                                                               ("Amanda", "Harper", "1986/11/05", 2500),
                                                                               ("Natalia", "Stewart", "1993/12/09", 2500),
                                                                               ("Todd", "Powell", "1984/10/19", 2500),
                                                                               ("Justin", "Dyer", "1988/09/17", 2500),
                                                                               ("Lily", "Huff", "1989/08/11", 2500),
                                                                               ("Philip", "West", "1983/09/15", 2500),
                                                                               ("Paulina", "Bishop", "1993/04/19", 2500),
                                                                               ("Max", "Leon", "1991/03/10", 2500),
                                                                               ("Scarlet", "Stafford", "1990/05/12", 2500),
                                                                               ("Cecelia", "Wheeler", "1986/09/25", 2500),
                                                                               ("Christina", "Moss", "1985/08/21", 2500),
                                                                               ("Natalia", "Hurley", "1989/09/23", 2500),
                                                                               ("Peter", "Jacobs", "1989/09/23", 2500),
                                                                               ("Lilliana", "Bennett", "1994/10/01", 2500),
                                                                               ("Luis", "Mclean", "1995/11/04", 2500),
                                                                               ("Jeremy", "Butler", "1984/02/09", 2500),
                                                                               ("Caroline", "Hooper", "1985/03/20", 2500),
                                                                               ("Leon", "Butler", "1988/09/22", 2500),
                                                                               ("Maya", "Morse", "1986/08/21", 2500),
                                                                               ("Erika", "Logan", "1989/05/17", 2500),
                                                                               ("John", "Collier", "1995/01/18", 2500),
                                                                               ("Anthony", "Donovan", "1994/03/11", 2500),
                                                                               ("Catherine", "Foster", "1990/11/19", 2500),
                                                                               ("Richard", "Steele", "1991/12/29", 2500),
                                                                               ("Luis", "Robinson", "1982/10/21", 2500),
                                                                               ("Jessica", "Griffin", "1983/05/09", 2500),
                                                                               ("Pamela", "Edward", "1986/06/10", 2500),
                                                                               ("Sean", "Weiser", "1985/02/15", 2500),
                                                                               ("Margaret", "Gonzales", "1989/03/12", 2500),
                                                                               ("Esther", "Duffy", "1990/01/18", 2500),
                                                                               ("Richard", "Warner", "1993/09/01", 2500),
                                                                               ("Catherine", "Stewart", "1991/11/06", 2500),
                                                                               ("Gerald", "Lake", "1988/07/30", 2500);
                                                                               
                                                                               
INSERT INTO trainers (first_name, last_name, subject) VALUES ("David", "Oster", "JavaScript"),
															 ("Sugar", "Sandra", "Python"),
                                                             ("Panagiotis", "Bozas", "C#"),
                                                             ("Chris", "Chitas", "Java"),
                                                             ("Lena", "Kapetanaki", "CSS"),
                                                             ("Danae", "Tzoumba", "SQL"),
                                                             ("Annalise", "Keating", "HTML"),
                                                             ("Charles", "Boyle", "CSS"),
                                                             ("Terry", "Jeffords", "SQL"),
                                                             ("Amy", "Santiago", "HTML"),
                                                             ("Harvey", "Specter", "JavaScript"),
                                                             ("Louis", "Litt", "Python"),
                                                             ("Mike", "Ross", "C#"),
                                                             ("Donna", "Paulsen", "Java"),
                                                             ("Barney", "Stinson", "JavaScript"),
                                                             ("Ted", "Mosby", "Python"),
                                                             ("Marshall", "Eriksen", "C#"),
                                                             ("Rachel", "Green", "Java");
                                                         
                                                            
INSERT INTO assignments (title, description, subDateTime, oral_mark, total_mark) VALUES ("Assignment1", "Description of 1st Assignment", "2021/11/29", 30, 60),
																						("Individual Project Part A", "Description of Individual Project Part A", "2021/12/21", 30, 60),
                                                                                        ("Individual Project Part B", "Description of Individual Project Part B", "2022/01/25", 30, 60),
                                                                                        ("Assignment2", "Description of 2nd Assignment", "2022/02/24", 30, 60),
                                                                                        ("Assignment3", "Description of 3rd Assignment", "2022/03/09", 30, 60),
                                                                                        ("Assignment4", "Description of 4th Assignment", "2022/03/15", 30, 60),
                                                                                        ("Assignment5", "Description of 5th Assignment", "2022/03/21", 30, 60),
                                                                                        ("Group Project", "Description of Group Project", "2022/04/26", 30, 60);
                                                                                        

INSERT INTO studentsPerCourse (student_id, course_id) VALUES (1, 1),
															 (2, 1),
															 (3, 1),
															 (4, 1),
															 (5, 1),
															 (6, 2),
															 (7, 2),
															 (8, 2),
															 (9, 2),
															 (10, 2),
															 (11, 3),
															 (12, 3),
															 (13, 3),
															 (14, 3),
															 (15, 3),
															 (16, 4),
															 (17, 4),
															 (18, 4),
															 (19, 4),
															 (20, 4),
															 (21, 5),
															 (22, 5),
															 (23, 5),
															 (24, 5),
															 (25, 5),
															 (26, 6),
															 (27, 6),
															 (28, 6),
															 (29, 6),
															 (30, 6),
															 (31, 7),
															 (32, 7),
															 (33, 7),
															 (34, 7),
															 (35, 7),
															 (36, 8),
															 (37, 8),
															 (38, 8),
															 (39, 8),
															 (40, 8),
															 (3, 4),
															 (13, 6),
															 (22, 8),
															 (31, 2);                     
                                                                                   
 
INSERT INTO trainersPerCourse (trainer_id, course_id) VALUES (1, 1),
															 (2, 3),
                                                             (3, 7),
                                                             (4, 5),
                                                             (5, 1),
                                                             (5, 2),
															 (5, 3),
                                                             (5, 4),
                                                             (6, 1),
                                                             (6, 2),
															 (6, 3),
                                                             (6, 4),
                                                             (7, 1),
                                                             (7, 2),
															 (7, 3),
                                                             (7, 4),
                                                             (8, 5),
                                                             (8, 6),
															 (8, 7),
                                                             (8, 8),
                                                             (9, 5),
                                                             (9, 6),
															 (9, 7),
                                                             (9, 8),
                                                             (10, 5),
                                                             (10, 6),
															 (10, 7),
                                                             (10, 8),
                                                             (11, 2),
                                                             (12, 4),
                                                             (13, 8),
                                                             (14, 6),
                                                             (15, 1),
                                                             (16, 3),
                                                             (17, 7),
                                                             (18, 5);
                                                             
                                                             
INSERT INTO assignmentsPerCourse (course_id, assignment_id) VALUES (1, 1),
																   (1, 2),
                                                                   (1, 3),
                                                                   (1, 4),
                                                                   (1, 5),
                                                                   (1, 6),
                                                                   (1, 7),
                                                                   (1, 8),
                                                                   (2, 1),
																   (2, 2),
                                                                   (2, 3),
                                                                   (2, 4),
                                                                   (2, 5),
                                                                   (2, 6),
                                                                   (2, 7),
                                                                   (2, 8),
                                                                   (3, 1),
																   (3, 2),
                                                                   (3, 3),
                                                                   (3, 4),
                                                                   (3, 5),
                                                                   (3, 6),
                                                                   (3, 7),
                                                                   (3, 8),
                                                                   (4, 1),
																   (4, 2),
                                                                   (4, 3),
                                                                   (4, 4),
                                                                   (4, 5),
                                                                   (4, 6),
                                                                   (4, 7),
                                                                   (4, 8),
                                                                   (5, 1),
																   (5, 2),
                                                                   (5, 3),
                                                                   (5, 4),
                                                                   (5, 5),
                                                                   (5, 6),
                                                                   (5, 7),
                                                                   (5, 8),
                                                                   (6, 1),
																   (6, 2),
                                                                   (6, 3),
                                                                   (6, 4),
                                                                   (6, 5),
                                                                   (6, 6),
                                                                   (6, 7),
                                                                   (6, 8),
                                                                   (7, 1),
																   (7, 2),
                                                                   (7, 3),
                                                                   (7, 4),
                                                                   (7, 5),
                                                                   (7, 6),
                                                                   (7, 7),
                                                                   (7, 8),
                                                                   (8, 1),
																   (8, 2),
                                                                   (8, 3),
                                                                   (8, 4),
                                                                   (8, 5),
                                                                   (8, 6),
                                                                   (8, 7),
                                                                   (8, 8);


INSERT INTO assignmentsPerStudentPerCourse (assignment_id, student_id, course_id) VALUES (1, 1, 1),
																						 (2, 1, 1),
                                                                                         (3, 1, 1),
                                                                                         (4, 1, 1),
                                                                                         (5, 1, 1),
                                                                                         (6, 1, 1),
                                                                                         (7, 1, 1),
                                                                                         (8, 1, 1),
                                                                                         (1, 2, 1),
                                                                                         (2, 2, 1),
                                                                                         (3, 2, 1),
                                                                                         (4, 2, 1),
                                                                                         (5, 2, 1),
                                                                                         (6, 2, 1),
                                                                                         (7, 2, 1),
                                                                                         (8, 2, 1),
                                                                                         (1, 3, 1),
                                                                                         (2, 3, 1),
                                                                                         (3, 3, 1),
                                                                                         (4, 3, 1),
                                                                                         (5, 3, 1),
                                                                                         (6, 3, 1),
                                                                                         (7, 3, 1),
                                                                                         (8, 3, 1),
                                                                                         (1, 4, 1),
                                                                                         (2, 4, 1),
                                                                                         (3, 4, 1),
                                                                                         (4, 4, 1),
                                                                                         (5, 4, 1),
                                                                                         (6, 4, 1),
                                                                                         (7, 4, 1),
                                                                                         (8, 4, 1),
                                                                                         (1, 5, 1),
                                                                                         (2, 5, 1),
                                                                                         (3, 5, 1),
                                                                                         (4, 5, 1),
                                                                                         (5, 5, 1),
                                                                                         (6, 5, 1),
                                                                                         (7, 5, 1),
                                                                                         (8, 5, 1),
                                                                                         (1, 6, 2),
                                                                                         (2, 6, 2),
                                                                                         (3, 6, 2),
                                                                                         (4, 6, 2),
                                                                                         (5, 6, 2),
                                                                                         (6, 6, 2),
                                                                                         (7, 6, 2),
                                                                                         (8, 6, 2),
                                                                                         (1, 7, 2),
                                                                                         (2, 7, 2),
                                                                                         (3, 7, 2),
                                                                                         (4, 7, 2),
                                                                                         (5, 7, 2),
                                                                                         (6, 7, 2),
                                                                                         (7, 7, 2),
                                                                                         (8, 7, 2),
                                                                                         (1, 8, 2),
                                                                                         (2, 8, 2),
                                                                                         (3, 8, 2),
                                                                                         (4, 8, 2),
                                                                                         (5, 8, 2),
                                                                                         (6, 8, 2),
                                                                                         (7, 8, 2),
                                                                                         (8, 8, 2),
                                                                                         (1, 9, 2),
                                                                                         (2, 9, 2),
                                                                                         (3, 9, 2),
                                                                                         (4, 9, 2),
                                                                                         (5, 9, 2),
                                                                                         (6, 9, 2),
                                                                                         (7, 9, 2),
                                                                                         (8, 9, 2),
                                                                                         (1, 10, 2),
                                                                                         (2, 10, 2),
                                                                                         (3, 10, 2),
                                                                                         (4, 10, 2),
                                                                                         (5, 10, 2),
                                                                                         (6, 10, 2),
                                                                                         (7, 10, 2),
                                                                                         (8, 10, 2),
                                                                                         (1, 11, 3),
                                                                                         (2, 11, 3),
                                                                                         (3, 11, 3),
                                                                                         (4, 11, 3),
                                                                                         (5, 11, 3),
                                                                                         (6, 11, 3),
                                                                                         (7, 11, 3),
                                                                                         (8, 11, 3),
                                                                                         (1, 12, 3),
                                                                                         (2, 12, 3),
                                                                                         (3, 12, 3),
                                                                                         (4, 12, 3),
                                                                                         (5, 12, 3),
                                                                                         (6, 12, 3),
                                                                                         (7, 12, 3),
                                                                                         (8, 12, 3),
                                                                                         (1, 13, 3),
                                                                                         (2, 13, 3),
                                                                                         (3, 13, 3),
                                                                                         (4, 13, 3),
                                                                                         (5, 13, 3),
                                                                                         (6, 13, 3),
                                                                                         (7, 13, 3),
                                                                                         (8, 13, 3),
                                                                                         (1, 14, 3),
                                                                                         (2, 14, 3),
                                                                                         (3, 14, 3),
                                                                                         (4, 14, 3),
                                                                                         (5, 14, 3),
                                                                                         (6, 14, 3),
                                                                                         (7, 14, 3),
                                                                                         (8, 14, 3),
                                                                                         (1, 15, 3),
                                                                                         (2, 15, 3),
                                                                                         (3, 15, 3),
                                                                                         (4, 15, 3),
                                                                                         (5, 15, 3),
                                                                                         (6, 15, 3),
                                                                                         (7, 15, 3),
                                                                                         (8, 15, 3),
                                                                                         (1, 16, 4),
                                                                                         (2, 16, 4),
                                                                                         (3, 16, 4),
                                                                                         (4, 16, 4),
                                                                                         (5, 16, 4),
                                                                                         (6, 16, 4),
                                                                                         (7, 16, 4),
                                                                                         (8, 16, 4),
                                                                                         (1, 17, 4),
                                                                                         (2, 17, 4),
                                                                                         (3, 17, 4),
                                                                                         (4, 17, 4),
                                                                                         (5, 17, 4),
                                                                                         (6, 17, 4),
                                                                                         (7, 17, 4),
                                                                                         (8, 17, 4),
                                                                                         (1, 18, 4),
                                                                                         (2, 18, 4),
                                                                                         (3, 18, 4),
                                                                                         (4, 18, 4),
                                                                                         (5, 18, 4),
                                                                                         (6, 18, 4),
                                                                                         (7, 18, 4),
                                                                                         (8, 18, 4),
                                                                                         (1, 19, 4),
                                                                                         (2, 19, 4),
                                                                                         (3, 19, 4),
                                                                                         (4, 19, 4),
                                                                                         (5, 19, 4),
                                                                                         (6, 19, 4),
                                                                                         (7, 19, 4),
                                                                                         (8, 19, 4),
                                                                                         (1, 20, 4),
                                                                                         (2, 20, 4),
                                                                                         (3, 20, 4),
                                                                                         (4, 20, 4),
                                                                                         (5, 20, 4),
                                                                                         (6, 20, 4),
                                                                                         (7, 20, 4),
                                                                                         (8, 20, 4),
                                                                                         (1, 21, 5),
                                                                                         (2, 21, 5),
                                                                                         (3, 21, 5),
                                                                                         (4, 21, 5),
                                                                                         (5, 21, 5),
                                                                                         (6, 21, 5),
                                                                                         (7, 21, 5),
                                                                                         (8, 21, 5),
                                                                                         (1, 22, 5),
                                                                                         (2, 22, 5),
                                                                                         (3, 22, 5),
                                                                                         (4, 22, 5),
                                                                                         (5, 22, 5),
                                                                                         (6, 22, 5),
                                                                                         (7, 22, 5),
                                                                                         (8, 22, 5),
                                                                                         (1, 23, 5),
                                                                                         (2, 23, 5),
                                                                                         (3, 23, 5),
                                                                                         (4, 23, 5),
                                                                                         (5, 23, 5),
                                                                                         (6, 23, 5),
                                                                                         (7, 23, 5),
                                                                                         (8, 23, 5),
                                                                                         (1, 24, 5),
                                                                                         (2, 24, 5),
                                                                                         (3, 24, 5),
                                                                                         (4, 24, 5),
                                                                                         (5, 24, 5),
                                                                                         (6, 24, 5),
                                                                                         (7, 24, 5),
                                                                                         (8, 24, 5),
                                                                                         (1, 25, 5),
                                                                                         (2, 25, 5),
                                                                                         (3, 25, 5),
                                                                                         (4, 25, 5),
                                                                                         (5, 25, 5),
                                                                                         (6, 25, 5),
                                                                                         (7, 25, 5),
                                                                                         (8, 25, 5),
                                                                                         (1, 26, 6),
                                                                                         (2, 26, 6),
                                                                                         (3, 26, 6),
                                                                                         (4, 26, 6),
                                                                                         (5, 26, 6),
                                                                                         (6, 26, 6),
                                                                                         (7, 26, 6),
                                                                                         (8, 26, 6),
                                                                                         (1, 27, 6),
                                                                                         (2, 27, 6),
                                                                                         (3, 27, 6),
                                                                                         (4, 27, 6),
                                                                                         (5, 27, 6),
                                                                                         (6, 27, 6),
                                                                                         (7, 27, 6),
                                                                                         (8, 27, 6),
                                                                                         (1, 28, 6),
                                                                                         (2, 28, 6),
                                                                                         (3, 28, 6),
                                                                                         (4, 28, 6),
                                                                                         (5, 28, 6),
                                                                                         (6, 28, 6),
                                                                                         (7, 28, 6),
                                                                                         (8, 28, 6),
                                                                                         (1, 29, 6),
                                                                                         (2, 29, 6),
                                                                                         (3, 29, 6),
                                                                                         (4, 29, 6),
                                                                                         (5, 29, 6),
                                                                                         (6, 29, 6),
                                                                                         (7, 29, 6),
                                                                                         (8, 29, 6),
                                                                                         (1, 30, 6),
                                                                                         (2, 30, 6),
                                                                                         (3, 30, 6),
                                                                                         (4, 30, 6),
                                                                                         (5, 30, 6),
                                                                                         (6, 30, 6),
                                                                                         (7, 30, 6),
                                                                                         (8, 30, 6),
                                                                                         (1, 31, 7),
                                                                                         (2, 31, 7),
                                                                                         (3, 31, 7),
                                                                                         (4, 31, 7),
                                                                                         (5, 31, 7),
                                                                                         (6, 31, 7),
                                                                                         (7, 31, 7),
                                                                                         (8, 31, 7),
                                                                                         (1, 32, 7),
                                                                                         (2, 32, 7),
                                                                                         (3, 32, 7),
                                                                                         (4, 32, 7),
                                                                                         (5, 32, 7),
                                                                                         (6, 32, 7),
                                                                                         (7, 32, 7),
                                                                                         (8, 32, 7),
                                                                                         (1, 33, 7),
                                                                                         (2, 33, 7),
                                                                                         (3, 33, 7),
                                                                                         (4, 33, 7),
                                                                                         (5, 33, 7),
                                                                                         (6, 33, 7),
                                                                                         (7, 33, 7),
                                                                                         (8, 33, 7),
                                                                                         (1, 34, 7),
                                                                                         (2, 34, 7),
                                                                                         (3, 34, 7),
                                                                                         (4, 34, 7),
                                                                                         (5, 34, 7),
                                                                                         (6, 34, 7),
                                                                                         (7, 34, 7),
                                                                                         (8, 34, 7),
                                                                                         (1, 35, 7),
                                                                                         (2, 35, 7),
                                                                                         (3, 35, 7),
                                                                                         (4, 35, 7),
                                                                                         (5, 35, 7),
                                                                                         (6, 35, 7),
                                                                                         (7, 35, 7),
                                                                                         (8, 35, 7),
                                                                                         (1, 36, 8),
                                                                                         (2, 36, 8),
                                                                                         (3, 36, 8),
                                                                                         (4, 36, 8),
                                                                                         (5, 36, 8),
                                                                                         (6, 36, 8),
                                                                                         (7, 36, 8),
                                                                                         (8, 36, 8),
                                                                                         (1, 37, 8),
                                                                                         (2, 37, 8),
                                                                                         (3, 37, 8),
                                                                                         (4, 37, 8),
                                                                                         (5, 37, 8),
                                                                                         (6, 37, 8),
                                                                                         (7, 37, 8),
                                                                                         (8, 37, 8),
                                                                                         (1, 38, 8),
                                                                                         (2, 38, 8),
                                                                                         (3, 38, 8),
                                                                                         (4, 38, 8),
                                                                                         (5, 38, 8),
                                                                                         (6, 38, 8),
                                                                                         (7, 38, 8),
                                                                                         (8, 38, 8),
                                                                                         (1, 39, 8),
                                                                                         (2, 39, 8),
                                                                                         (3, 39, 8),
                                                                                         (4, 39, 8),
                                                                                         (5, 39, 8),
                                                                                         (6, 39, 8),
                                                                                         (7, 39, 8),
                                                                                         (8, 39, 8),
                                                                                         (1, 40, 8),
                                                                                         (2, 40, 8),
                                                                                         (3, 40, 8),
                                                                                         (4, 40, 8),
                                                                                         (5, 40, 8),
                                                                                         (6, 40, 8),
                                                                                         (7, 40, 8),
                                                                                         (8, 40, 8),
                                                                                         (1, 3, 4),
                                                                                         (2, 3, 4),
                                                                                         (3, 3, 4),
                                                                                         (4, 3, 4),
                                                                                         (5, 3, 4),
                                                                                         (6, 3, 4),
                                                                                         (7, 3, 4),
                                                                                         (8, 3, 4),
                                                                                         (1, 13, 6),
                                                                                         (2, 13, 6),
                                                                                         (3, 13, 6),
                                                                                         (4, 13, 6),
                                                                                         (5, 13, 6),
                                                                                         (6, 13, 6),
                                                                                         (7, 13, 6),
                                                                                         (8, 13, 6),
                                                                                         (1, 22, 8),
                                                                                         (2, 22, 8),
                                                                                         (3, 22, 8),
                                                                                         (4, 22, 8),
                                                                                         (5, 22, 8),
                                                                                         (6, 22, 8),
                                                                                         (7, 22, 8),
                                                                                         (8, 22, 8),
                                                                                         (1, 31, 2),
                                                                                         (2, 31, 2),
                                                                                         (3, 31, 2),
                                                                                         (4, 31, 2),
                                                                                         (5, 31, 2),
                                                                                         (6, 31, 2),
                                                                                         (7, 31, 2),
                                                                                         (8, 31, 2);
                                                                                         
                                                                                         
                                                                                         
-- A list of all the students
SELECT * FROM students;

-- A list of all the trainers
SELECT * FROM trainers;

-- A list of all the assignments
SELECT * FROM assignments;

-- A list of all the courses
SELECT * FROM courses;

-- All the students per course
SELECT * FROM students_Per_Course;

CREATE VIEW students_Per_Course AS
SELECT c.title, c.stream, c.type, s.first_name, s.last_name
FROM students AS s, courses AS c, studentsPerCourse AS spc
WHERE s.student_id = spc.student_id AND c.course_id = spc.course_id
ORDER BY c.title;


-- All the trainers per course
SELECT * FROM trainers_Per_Course;

CREATE VIEW trainers_Per_Course AS
SELECT c.title, c.stream, c.type, t.first_name, t.last_name
FROM courses AS c, trainers AS t, trainersPerCourse AS tpc
WHERE c.course_id = tpc.course_id AND t.trainer_id = tpc.trainer_id  
ORDER BY c.title;


-- All the assignments per course
SELECT * FROM assignments_Per_Course;

CREATE VIEW assignments_Per_Course AS
SELECT c.title as courseTitle, c.stream, c.type, a.title, a.description
FROM courses AS c, assignments AS a, assignmentsPerCourse AS apc
WHERE c.course_id = apc.course_id AND a.assignment_id = apc.assignment_id
ORDER BY c.title;


-- All the assignments per course per student
SELECT * FROM assignments_Per_Student_Per_Course;

CREATE VIEW assignments_Per_Student_Per_Course AS
SELECT assignments.title, assignments.subDateTime, courses.stream, courses.type, students.first_name, students.last_name
FROM assignmentsPerStudentPerCourse 
INNER JOIN assignments ON assignmentsPerStudentPerCourse.assignment_id = assignments.assignment_id
INNER JOIN courses ON assignmentsPerStudentPerCourse.course_id = courses.course_id
INNER JOIN students ON assignmentsPerStudentPerCourse.student_id = students.student_id;


-- A list of students that belong to more than one courses
SELECT * FROM studentsToMoreThanOneCourse;

CREATE VIEW studentsToMoreThanOneCourse AS
SELECT  students.student_id, students.first_name, students.last_name, COUNT(*) AS Number_Of_Courses
FROM students
INNER JOIN studentsPerCourse ON studentsPerCourse.student_id = students.student_id
INNER JOIN courses ON studentsPerCourse.course_id = courses.course_id
GROUP BY students.student_id
HAVING COUNT(*) > 1
ORDER BY students.student_id;
